build: use Janino specified by spring-boot
or our build will fail because logback faces NoClassDefFoundError:
https://github.com/spring-projects/spring-boot/issues/20728#issuecomment-606527012